### ISSUE TITLE
Correct Phone Size vs. PC Size Differences

### ISSUE THREAD

**Issue by aamick** [publicservantsprayer/repsp#1]
Correct Phone Size vs. PC Size differences
Main issues including:

-Nav bar is not the same and does not work in the PC size
-Public Servants' Prayer header is half covered up in PC size
-Leader's Pictures are too pixilated in PC size
-The map stays the small size on PC screen
-Main page posts from 2 weeks past, dates are scrunched and maybe should be moved to a bar at the top instead of side view
-Updates don't grow with the PC screen and look really bad

**Comment by namick** [comment]
These should be fixed now.
